# Generated by Django 6.0.2 on 2026-02-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.CharField(choices=[('programacion', 'Programación'), ('circuitos', 'Circuitos'), ('bases_datos', 'Bases de Datos'), ('sistemas', 'Sistemas Operativos')], default='programacion', max_length=50),
            preserve_default=False,
        ),
    ]
