# Generated by Django 6.0.2 on 2026-02-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.CharField(choices=[('programacion', 'Programación'), ('circuitos', 'Circuitos'), ('bases_datos', 'Bases de Datos'), ('sistemas', 'Sistemas Operativos')], max_length=20),
        ),
    ]
