# Generated by Django 6.0.3 on 2026-03-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_descripcion_remove_video_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='archivo',
        ),
        migrations.AddField(
            model_name='video',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(default='Sin descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.CharField(choices=[('programacion', 'Programación'), ('circuitos', 'Circuitos'), ('bases_datos', 'Bases de Datos'), ('sistemas', 'Sistemas Operativos')], max_length=50),
        ),
    ]
