# Generated by Django 6.0.3 on 2026-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_archivo_video_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default='dQw4w9WgXcQ', max_length=20),
            preserve_default=False,
        ),
    ]
