# Generated by Django 6.0.3 on 2026-03-07 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
