# Generated by Django 6.0.3 on 2026-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_delete_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='activo',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(default='https://youtube.com', verbose_name='Link de YouTube'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.CharField(choices=[('programacion', 'Programación'), ('circuitos', 'Circuitos'), ('bases_datos', 'Bases de Datos'), ('sistemas', 'Sistemas Operativos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
