# Generated by Django 6.0.3 on 2026-03-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensajeContacto',
        ),
    ]
